---

services:
  proxy:
    image: caddy:2.8.4
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
  backend:
    build: src
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo:8.0.3"
